#!/usr/bin/env bash
set -eu

echo "🔵 build"
source hooks/.config

echo "✅ Will build the following architectures: $(IFS=, ; echo "${build_architectures[@]}")"
echo "⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯"

for arch in ${build_architectures[@]}; do
  echo "✅ building $arch"
  echo "⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯"

  JACKETT_ARCH=${jackett_arch_map[${arch}]}
  JACKETT_RELEASE=$(curl -k -s "https://api.github.com/repos/Jackett/Jackett/releases" | jq -r '.[0] | .tag_name') 
  JACKETT_URL=$(curl -k -s "https://api.github.com/repos/Jackett/Jackett/releases/tags/${JACKETT_RELEASE}" | jq -r '.assets[].browser_download_url' | grep ${JACKETT_ARCH})

  docker exec docker_daemon docker build \
    --squash \
    --platform=${arch} \
    --build-arg BASE_IMAGE_PREFIX=${base_image_prefix_map[${arch}]} \
    --build-arg ARCH=${arch} \
    --build-arg JACKETT_RELEASE=${JACKETT_RELEASE} \
    --build-arg JACKETT_ARCH=${JACKETT_ARCH} \
    --build-arg JACKETT_URL=${JACKETT_URL} \
    --file /build/$DOCKERFILE_PATH \
    --tag "${IMAGE_NAME}-${arch}"  \
    /build
done

echo "✅ images built:"
echo "⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯"
docker exec docker_daemon docker image ls

trap "exit 1"          HUP INT PIPE QUIT TERM